nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
Failure: OSError (No such file /home/mujina/prog/Python/addrbook/2) ... ERROR

======================================================================
ERROR: Failure: OSError (No such file /home/mujina/prog/Python/addrbook/2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mujina/prog/Python/tg2py3.6env/lib/python3.6/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /home/mujina/prog/Python/addrbook/2

----------------------------------------------------------------------
Ran 1 test in 0.076s

FAILED (errors=1)
